# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzg9nzAxwQKUKHEPRgD17N7fxM6U1ZZj
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('restaurant_sales_datanew.csv')
df.head()

df.describe()

"""Handle Missing Values"""

df.isnull().sum()

"""Remove Duplicates"""

df.drop_duplicates(inplace=True)

"""Fix Data Types"""

df['date'] = pd.to_datetime(df['date'], errors='coerce')

df['Sales'] = df['actual_selling_price'] * df['quantity_sold']
df['Cost'] = df['typical_ingredient_cost'] * df['quantity_sold']
df['Profit'] = df['Sales'] - df['Cost']

df.info()
df.head()

df.to_csv('cleaned_restaurant_data.csv', index=False)

files.download('cleaned_restaurant_data.csv')